-- Optional infrastructure for the one-way Google Sheets mirror.
-- No domain-table triggers are installed: call enqueue_google_sheets_sync()
-- from the transaction that changes a mirrored entity.

create extension if not exists pgcrypto;

create table if not exists public.sync_outbox (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  operation text not null default 'upsert'
    check (operation in ('upsert', 'delete')),
  payload jsonb not null default '{}'::jsonb,
  source_updated_at timestamptz,
  revision bigint not null default 1 check (revision > 0),
  status text not null default 'pending'
    check (status in ('pending', 'synced', 'error')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz not null default now(),
  locked_at timestamptz,
  claim_token uuid,
  synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (entity_type, entity_id)
);

create index if not exists sync_outbox_pending_idx
  on public.sync_outbox (next_attempt_at, id)
  where status = 'pending';

alter table public.sync_outbox enable row level security;

revoke all on table public.sync_outbox from anon, authenticated;

create or replace function public.enqueue_google_sheets_sync(
  p_entity_type text,
  p_entity_id text,
  p_operation text default 'upsert',
  p_payload jsonb default '{}'::jsonb,
  p_source_updated_at timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_entity_type text := lower(trim(p_entity_type));
  v_entity_id text := trim(p_entity_id);
begin
  if v_entity_type not in (
    'employee', 'employees',
    'product', 'products',
    'period', 'periods',
    'sale', 'sales',
    'calculation', 'calculations',
    'setting', 'settings',
    'audit'
  ) then
    raise exception 'Unsupported Google Sheets entity type: %', v_entity_type;
  end if;

  if v_entity_id = '' then
    raise exception 'Entity id must not be empty';
  end if;

  if p_operation not in ('upsert', 'delete') then
    raise exception 'Unsupported sync operation: %', p_operation;
  end if;

  insert into public.sync_outbox as current_row (
    entity_type,
    entity_id,
    operation,
    payload,
    source_updated_at
  )
  values (
    v_entity_type,
    v_entity_id,
    p_operation,
    coalesce(p_payload, '{}'::jsonb),
    p_source_updated_at
  )
  on conflict (entity_type, entity_id) do update
  set operation = excluded.operation,
      payload = excluded.payload,
      source_updated_at = excluded.source_updated_at,
      revision = current_row.revision + 1,
      status = 'pending',
      attempts = 0,
      next_attempt_at = now(),
      synced_at = null,
      last_error = null,
      updated_at = now()
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.enqueue_google_sheets_sync(
  text, text, text, jsonb, timestamptz
) from public, anon, authenticated;
grant execute on function public.enqueue_google_sheets_sync(
  text, text, text, jsonb, timestamptz
) to service_role;

create or replace function public.claim_google_sheets_sync(
  p_batch_size integer default 50,
  p_lease_seconds integer default 300,
  p_max_attempts integer default 8
)
returns table (
  outbox_id text,
  entity_type text,
  entity_id text,
  operation text,
  payload jsonb,
  source_updated_at timestamptz,
  revision bigint,
  claim_token uuid,
  attempts integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select o.id
    from public.sync_outbox o
    where o.status = 'pending'
      and (
        o.attempts < greatest(1, p_max_attempts)
        or o.claim_token is not null
      )
      and o.next_attempt_at <= now()
      and (
        o.claim_token is null
        or o.locked_at < now() - make_interval(
          secs => greatest(30, p_lease_seconds)
        )
      )
    order by o.next_attempt_at, o.id
    for update skip locked
    limit least(greatest(1, p_batch_size), 200)
  ),
  claimed as (
    update public.sync_outbox o
    set attempts = o.attempts + 1,
        locked_at = now(),
        claim_token = gen_random_uuid(),
        last_error = null,
        updated_at = now()
    from candidates c
    where o.id = c.id
    returning o.*
  )
  select
    c.id::text,
    c.entity_type,
    c.entity_id,
    c.operation,
    c.payload,
    c.source_updated_at,
    c.revision,
    c.claim_token,
    c.attempts
  from claimed c
  order by c.id;
end;
$$;

revoke all on function public.claim_google_sheets_sync(
  integer, integer, integer
) from public, anon, authenticated;
grant execute on function public.claim_google_sheets_sync(
  integer, integer, integer
) to service_role;

grant select, insert, update on table public.sync_outbox to service_role;
grant usage, select on sequence public.sync_outbox_id_seq to service_role;

comment on table public.sync_outbox is
  'Transactional outbox for the one-way Google Sheets mirror.';
comment on function public.enqueue_google_sheets_sync(
  text, text, text, jsonb, timestamptz
) is
  'Idempotently queues the newest snapshot for one mirrored entity.';
